### ISSUE TITLE
Improve sales page by tabulating sales data

### ISSUE THREAD

**Issue by Gajjela-Koushik-Reddy** [ChicoState/PantryNode#129]
As of now the sales page consists of only the type of items but it does not show any detailed data for the individual items.
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/40049731/231260566-3c9b54cc-6c02-4cd4-b033-062df0660a4c.png">

**Comment by KishoreMenda** [comment]
using npm react-table for this

**Comment by AbhinavReddy-Dev** [comment]
This is nice that you guys have started working on this issue. One suggestion is that please create a `feature_branch` from `frontend` to develop, and then create a pull request to `frontend` instead of directly working on frontend and committing to  it. [This](https://github.com/ChicoState/PantryNode/commit/582c0661d0874edcd0a4c15602a30dab17a84109) commit is untracked for the commit to the `main` branch. Please be aware of this issue of committing your code into `frontend` directly.

So the flow goes like this:

1. Check if `frontend` is up to date with `main`.

2. Checkout new `feature_branch` from `frontend`.

3. Develop in `feature_branch`.

4. Create a pull request from `feature_branch` to `frontend` and request for a review before squash and merge.

5. Immediately, create a pull request from `frontend` to `main` for rebase and merge.

**Comment by hardikpatil** [comment]
> This is nice that you guys have started working on this issue. One suggestion is that please create a `feature_branch` from `frontend` to develop, and then create a pull request to `frontend` instead of directly working on frontend and committing to it. [This](https://github.com/ChicoState/PantryNode/commit/582c0661d0874edcd0a4c15602a30dab17a84109) commit is untracked for the commit to the `main` branch. Please be aware of this issue of committing your code into `frontend` directly.
> 
> So the flow goes like this:
> 
> 1. Check if `frontend` is up to date with `main`.
> 2. Checkout new `feature_branch` from `frontend`.
> 3. Develop in `feature_branch`.
> 4. Create a pull request from `feature_branch` to `frontend` and request for a review before squash and merge.
> 5. Immediately, create a pull request from `frontend` to `main` for rebase and merge.

Agreed, also this is a duplicate issue, the original one is #102 and was assigned to @DevangRaval1 @prasannarajezzzy @TJSidhu1
