### ISSUE TITLE
Clean up linter rule overrides

### ISSUE THREAD

**Issue by Jooms** [ChicoState/PantryNode#47]
> I'm thinking close this issue and open a fresh one regarding cleaning up all the warnings and reinstating the errors?

A continuation of #19 

#40 Added 3 linter rule overrides when adding the linter to CI. These need to be cleaned up (removed).
It was also identified that we should add a step for "how to run the linter locally" to the README.md.

- [x] Clean up **@typescript-eslint/no-var-requires**
- [x] #48
- [x] Clean up **no-undef** #103 
- [x] Add "how to run the linter locally" to the README.md - #50 

"Clean up ..." entails 2 steps
1. Remove the overridden rule in the eslintrc.cjs
2. Update the code so all errors are fixed.

**Comment by ysiddhapura** [comment]
I can take the first task - Clean up @typescript-eslint/no-var-requires

**Comment by parthpandey1** [comment]
I can take the second task Clean up @typescript-eslint/no-extra-semi

**Comment by Anoushka444** [comment]
I can take up third Clean up no-undef

**Comment by jayrevolinskyjr** [comment]
I'll take task four, README instructions for running linter locally

**Comment by ysiddhapura** [comment]
As I'm working on the no-var-requires errors, creates by the linter, through my research I found there is new syntax which changes 
var foo = require('foo');
to..
import foo = require('foo');
require('foo');

It is not a requirement to use this syntax, as mentioned here [https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-var-requires.md]

Although when I did change the syntax to match the new version and ran the entire application, it gave me a syntax error, but the linter marked my error as resolved. 

So, I'm thinking, we should just leave the  no-var-requires linter error as a warning and leave the code as is, since it's running fine without the syntax changes. 

What does everyone think?

**Comment by AbhinavReddy-Dev** [comment]
Hey! wanted to know if anyone is working on getting the linter work locally for running it once before making a merge or a pull request, I know that the linter is working on GitHub workflows. We are expecting a surge in frontend code in the coming days, a linter locally will help a ton. Please let me know, I can work with anyone interested to set it up for React.

**Comment by AbhinavReddy-Dev** [comment]
> I'll take task four, README instructions for running linter locally

Can we make the install a one time thing and only run the eslint command everytime? What I mean is that the `npm install --save-dev ....` can be run only once and when someone clones/ forks the project, one time `npm install` will install the dependencies for eslint as well. Please let me know if I'm missing anything that is making us take this approach.

**Comment by jayrevolinskyjr** [comment]
> > I'll take task four, README instructions for running linter locally
> 
> Can we make the install a one time thing and only run the eslint command everytime? What I mean is that the `npm install --save-dev ....` can be run only once and when someone clones/ forks the project, one time `npm install` will install the dependencies for eslint as well. Please let me know if I'm missing anything that is making us take this approach.

That's a good point, we were considering an install of just ESLint. The task would just require making sure that the linter is included in the `npm install` and/or meshing all the packages together once the project is ready for feature development.

**Comment by AbhinavReddy-Dev** [comment]
> > > I'll take task four, README instructions for running linter locally
> > 
> > 
> > Can we make the install a one time thing and only run the eslint command everytime? What I mean is that the `npm install --save-dev ....` can be run only once and when someone clones/ forks the project, one time `npm install` will install the dependencies for eslint as well. Please let me know if I'm missing anything that is making us take this approach.
> 
> That's a good point, we were considering an install of just ESLint. The task would just require making sure that the linter is included in the `npm install` and/or meshing all the packages together once the project is ready for feature development.

Yes, that way the linter packages would be installed with `npm install`. Also, it would be great if we can rollout the support for react-app as well in the next push. Let me know if you need any help in setting it up.

**Comment by jayrevolinskyjr** [comment]
> As I'm working on the no-var-requires errors, creates by the linter, through my research I found there is new syntax which changes var foo = require('foo'); to.. import foo = require('foo'); require('foo');
> 
> It is not a requirement to use this syntax, as mentioned [here](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-var-requires.md)
> 
> Although when I did change the syntax to match the new version and ran the entire application, it gave me a syntax error, but the linter marked my error as resolved.
> 
> So, I'm thinking, we should just leave the no-var-requires linter error as a warning and leave the code as is, since it's running fine without the syntax changes.
> 
> What does everyone think?

What sort of syntax error was it producing? If it's real bad then it might not be worth the effort.

 The new syntax is easier to read but not necessary. I think the priority should be to keep the code consistent.

**Comment by ysiddhapura** [comment]
> > As I'm working on the no-var-requires errors, creates by the linter, through my research I found there is new syntax which changes var foo = require('foo'); to.. import foo = require('foo'); require('foo');
> > It is not a requirement to use this syntax, as mentioned [here](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-var-requires.md)
> > Although when I did change the syntax to match the new version and ran the entire application, it gave me a syntax error, but the linter marked my error as resolved.
> > So, I'm thinking, we should just leave the no-var-requires linter error as a warning and leave the code as is, since it's running fine without the syntax changes.
> > What does everyone think?
> 
> What sort of syntax error was it producing? If it's real bad then it might not be worth the effort.
> 
> The new syntax is easier to read but not necessary. I think the priority should be to keep the code consistent.

I'm getting a syntax error which says : Cannot use import statement outside a module.

**Comment by jayrevolinskyjr** [comment]
> I'm getting a syntax error which says : Cannot use import statement outside a module.

As discussed during the SCRUM meeting, keeping it as a warning will work for now. Any potential to just suppress the warning entirely?

**Comment by ysiddhapura** [comment]
> > I'm getting a syntax error which says : Cannot use import statement outside a module.
> 
> As discussed during the SCRUM meeting, keeping it as a warning will work for now. Any potential to just suppress the warning entirely?

Let's just leave it as is right now which is a warning, just because I'm not sure how it will affect the project overall, but in the future we can suppress if needed. Marked the @typescript-eslint/no-var-requires clean up lint task as done.

**Comment by Anoushka444** [comment]
I was working on the no-undef lint task-3. Findings and blockers:

1. I fixed the no-undef in all files.

2. For some of the variables in file location- PantryNode\models\init-models.ts, 
It shows no-undef error however the variable are already defined. My guess is that since these variables are defined inside a function and unable to be accessed outside of it, lint is throwing no-undef error!

Might be fixed if I declare them globally but that may lead to other conflicts since the variables could be accessible from everywhere. My take on this is to research more and find a solution that keeps the variable scoped within the function that uses it. Need everyone's take on that. What does everyone think?

**Comment by jayrevolinskyjr** [comment]
> I was working on the no-undef lint task-3. Findings and blockers:
> 
>     1. I fixed the no-undef in all files.
> 
>     2. For some of the variables in file location- PantryNode\models\init-models.ts,
>        It shows no-undef error however the variable are already defined. My guess is that since these variables are defined inside a function and unable to be accessed outside of it, lint is throwing no-undef error!
> 
> 
> Might be fixed if I declare them globally but that may lead to other conflicts since the variables could be accessible from everywhere. My take on this is to research more and find a solution that keeps the variable scoped within the function that uses it. Need everyone's take on that. What does everyone think?

Which specific variables are causing the no-undef error to be tossed on your machine?

 It might be that those specific variables are tossing the no-undef error because they were originally intended as global variables, even though they are not explicitly [marked](https://eslint.org/docs/latest/rules/no-undef.html). 

My intuition says to avoid global variables for the reason that you mentioned, but whether we use global variables or not should be brought up in-class.

**Comment by AbhinavReddy-Dev** [comment]
Can we please close this issue as all the task have been checked?

**Comment by Anoushka444** [comment]
Closing this as all issues checked.
